import re

with open('app/src/main/java/com/example/util/CsvExportHelper.kt', 'r') as f:
    code = f.read()

# Replace the formatting logic
replacement = """
    fun generateCsvString(expenses: List<ExpenseEntity>, householdName: String = "Household"): String {
        val dateFormat = SimpleDateFormat("MMM dd, yyyy", Locale.getDefault())
        val monthFormat = SimpleDateFormat("MMMM yyyy", Locale.getDefault())
        val currentMonthName = monthFormat.format(Date())
        val sb = StringBuilder()

        sb.append("=====================================\n")
        sb.append("   ${householdName.uppercase(Locale.getDefault())} EXPENSE REPORT\n")
        sb.append("   $currentMonthName\n")
        sb.append("=====================================\n\n")

        val totalSum = expenses.sumOf { it.amount }
        val currency = expenses.firstOrNull()?.currencySymbol ?: "$"
        sb.append("TOTAL SPENT: $currency${String.format(Locale.US, "%.2f", totalSum)}\n\n")
        
        sb.append("-------------------------------------\n")
        sb.append("          EXPENSE DETAILS\n")
        sb.append("-------------------------------------\n\n")

        val groupedExpenses = expenses.groupBy { dateFormat.format(Date(it.timestamp)) }

        for ((dateStr, dailyExpenses) in groupedExpenses) {
            sb.append("🗓️ $dateStr\n")
            sb.append(".....................................\n")
            for (expense in dailyExpenses) {
                val amountFormatted = "${expense.currencySymbol}${String.format(Locale.US, "%.2f", expense.amount)}"
                sb.append(" • ${expense.description}\n")
                sb.append("   Amount:   $amountFormatted\n")
                sb.append("   Paid By:  ${expense.paidByMemberName}\n")
                sb.append("   Category: ${expense.category}\n")
                if (expense.note.isNotBlank()) {
                    sb.append("   Note:     ${expense.note}\n")
                }
                sb.append("\n")
            }
        }
        
        sb.append("=====================================\n")
        sb.append("Generated by FamSpend App\n")

        return sb.toString()
    }
"""
code = re.sub(r'fun generateCsvString\(.*?\)\: String \{.*?(?=private fun escapeCsv)', replacement, code, flags=re.DOTALL)

# Replace .csv with .txt
code = code.replace('.csv"', '.txt"')
# Replace text/csv with text/plain
code = code.replace('"text/csv"', '"text/plain"')
code = code.replace('Export Expenses CSV', 'Export Expenses Report')
code = code.replace('Expenses Export (CSV)', 'Expenses Export')

with open('app/src/main/java/com/example/util/CsvExportHelper.kt', 'w') as f:
    f.write(code)
