new_code = """package com.example.util

import android.content.Context
import android.content.Intent
import android.net.Uri
import androidx.core.content.FileProvider
import com.example.data.model.ExpenseEntity
import java.io.File
import java.io.FileWriter
import java.text.SimpleDateFormat
import java.util.Calendar
import java.util.Date
import java.util.Locale

object CsvExportHelper {

    /**
     * Filters expenses belonging to the current month and year.
     */
    fun filterCurrentMonthExpenses(expenses: List<ExpenseEntity>): List<ExpenseEntity> {
        val calendar = Calendar.getInstance()
        val currentMonth = calendar.get(Calendar.MONTH)
        val currentYear = calendar.get(Calendar.YEAR)
        
        return expenses.filter { expense ->
            val expCal = Calendar.getInstance().apply { timeInMillis = expense.timestamp }
            expCal.get(Calendar.MONTH) == currentMonth && expCal.get(Calendar.YEAR) == currentYear
        }.sortedByDescending { it.timestamp }
    }

    /**
     * Formats current month's expenses list into a readable text report string.
     */
    fun generateCsvString(expenses: List<ExpenseEntity>, householdName: String = "Household"): String {
        val dateFormat = SimpleDateFormat("MMM dd, yyyy", Locale.getDefault())
        val monthFormat = SimpleDateFormat("MMMM yyyy", Locale.getDefault())
        val currentMonthName = monthFormat.format(Date())
        val sb = StringBuilder()

        sb.append("=====================================\\n")
        sb.append("   ${householdName.uppercase(Locale.getDefault())} EXPENSE REPORT\\n")
        sb.append("   $currentMonthName\\n")
        sb.append("=====================================\\n\\n")

        val totalSum = expenses.sumOf { it.amount }
        val currency = expenses.firstOrNull()?.currencySymbol ?: "$"
        sb.append("TOTAL SPENT: $currency${String.format(Locale.US, "%.2f", totalSum)}\\n\\n")
        
        sb.append("-------------------------------------\\n")
        sb.append("          EXPENSE DETAILS\\n")
        sb.append("-------------------------------------\\n\\n")

        val groupedExpenses = expenses.groupBy { dateFormat.format(Date(it.timestamp)) }

        for ((dateStr, dailyExpenses) in groupedExpenses) {
            sb.append("🗓️ $dateStr\\n")
            sb.append(".....................................\\n")
            for (expense in dailyExpenses) {
                val amountFormatted = "${expense.currencySymbol}${String.format(Locale.US, "%.2f", expense.amount)}"
                sb.append(" • ${expense.description}\\n")
                sb.append("   Amount:   $amountFormatted\\n")
                sb.append("   Paid By:  ${expense.paidByMemberName}\\n")
                sb.append("   Category: ${expense.category}\\n")
                if (expense.note.isNotBlank()) {
                    sb.append("   Note:     ${expense.note}\\n")
                }
                sb.append("\\n")
            }
        }
        
        sb.append("=====================================\\n")
        sb.append("Generated by FamSpend App\\n")

        return sb.toString()
    }

    /**
     * Shares or saves the report file using Android's native share sheet.
     */
    fun shareCsvFile(context: Context, csvData: String, householdName: String = "Household"): Boolean {
        val monthFileFormat = SimpleDateFormat("yyyy_MM", Locale.getDefault()).format(Date())
        val cleanHousehold = householdName.replace("\\\\s+".toRegex(), "_")
        val filename = "Expenses_${cleanHousehold}_${monthFileFormat}.txt"
        
        return try {
            val cacheDir = File(context.cacheDir, "exports")
            if (!cacheDir.exists()) {
                cacheDir.mkdirs()
            }
            val file = File(cacheDir, filename)
            FileWriter(file).use { writer ->
                writer.write(csvData)
            }

            val contentUri: Uri = FileProvider.getUriForFile(
                context,
                "${context.packageName}.fileprovider",
                file
            )

            val shareIntent = Intent(Intent.ACTION_SEND).apply {
                type = "text/plain"
                putExtra(Intent.EXTRA_SUBJECT, "$householdName Expenses Report - $monthFileFormat")
                putExtra(Intent.EXTRA_TEXT, "Attached is the text report of household expenses for $monthFileFormat.")
                putExtra(Intent.EXTRA_STREAM, contentUri)
                addFlags(Intent.FLAG_GRANT_READ_URI_PERMISSION)
            }
            val chooser = Intent.createChooser(shareIntent, "Export Expenses Report")
            chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
            context.startActivity(chooser)
            true
        } catch (e: Exception) {
            e.printStackTrace()
            try {
                val sendIntent = Intent(Intent.ACTION_SEND).apply {
                    type = "text/plain"
                    putExtra(Intent.EXTRA_SUBJECT, "$householdName Expenses Report")
                    putExtra(Intent.EXTRA_TEXT, csvData)
                }
                val chooser = Intent.createChooser(sendIntent, "Export Expenses Report")
                chooser.addFlags(Intent.FLAG_ACTIVITY_NEW_TASK)
                context.startActivity(chooser)
                true
            } catch (ex: Exception) {
                ex.printStackTrace()
                false
            }
        }
    }
}
"""

with open('app/src/main/java/com/example/util/CsvExportHelper.kt', 'w') as f:
    f.write(new_code.replace("\\n", "\n").replace("\\\\s", "\\s"))
